02-modal
js-tasks-ru/htmlcss-20220210_schyotkina-anna pull request #10
Opened 2022-02-26 22:17 UTC by ShchetkinaAnna

2022-02-26 22:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-27 10:05 UTC, GSemikozov requested changes

2022-02-27 10:05 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    display: none;
фон укажем здесь используя grba

2022-02-27 10:05 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__background {
а этот лишний элемент удалим

2022-02-27 10:05 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
здесь будем использовать absolute / relative - достаточно 1 раз на уровне блока задать fixed

2022-02-27 10:05 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
можно также обойтись без __container, указав необходимые значения на __window (поскольку .modal уже и так закрыл собой весь viewport - остается лишь выравнять __window внутри)

2022-02-27 15:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-27 17:53 UTC, GSemikozov approved these changes

2022-02-27 17:53 UTC, merged