Main page
js-tasks-ru/htmlcss-20220210_schyotkina-anna pull request #25
Opened 2022-03-14 19:51 UTC by ShchetkinaAnna

2022-03-14 19:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-15 21:05 UTC, GSemikozov requested changes

2022-03-15 21:05 UTC, GSemikozov commented on components/card/card.css
> +.card__calendar {
элемент в карточке для каждого встраиваемого компонента? то есть на каждый новый компонент придется в другом компоненте (картчоке) создавать новых класс-элемент? Нет, это будет не универсально) нужно просто сделать общие отступы (паддинги) в превью карточки, а встраиваемые компоненты центрировать, а если надо ограничить по ширине - то через модификатор самого встраиваемого компонента)

2022-03-15 21:05 UTC, GSemikozov commented on components/card/card.css
> +.card__calendar {
и ниже то же самое

2022-03-16 19:15 UTC, GSemikozov approved these changes

2022-03-16 19:15 UTC, merged