add dz 01-button
js-tasks-ru/htmlcss-20220210_schyotkina-anna pull request #3
Opened 2022-02-19 20:34 UTC by ShchetkinaAnna

2022-02-19 20:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-19 21:08 UTC, GSemikozov requested changes

2022-02-19 21:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    height: 50px;
не соответствует дизайну)

2022-02-19 21:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 200px;
лучше жестко не фиксировать ширину - пусть определяется внутренним содержимым

2022-02-19 21:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-style: solid;
и тогда border-color - transparent

2022-02-19 21:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    opacity: 0.33;
0.5

2022-02-19 21:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
лучше сразу pointer-event: none

2022-02-19 21:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary, .button_primary:disabled {
disabled общий, достаточно на уровне блока, для модификаторов не надо отдельно задавать

2022-02-20 15:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-20 16:32 UTC, ShchetkinaAnna commented on 03-lection1/01-button/button.css
> +    height: 50px;
Не уверена, что верно поняла, что именно не соответствует, но убрала фиксированные высоту и ширину и сделала отступ через padding + задала min-width. Это имелось в виду?

2022-02-20 16:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-20 19:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-20 20:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-22 15:57 UTC, GSemikozov approved these changes

2022-02-22 15:57 UTC, merged