02-accordion
js-tasks-ru/htmlcss-20220210_schyotkina-anna pull request #4
Opened 2022-02-21 20:29 UTC by ShchetkinaAnna

2022-02-21 20:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-22 16:00 UTC, GSemikozov requested changes

2022-02-22 16:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion-item {
.accordion__accordion-item

2022-02-22 16:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion-item__summary {
.accordion__summary

2022-02-22 16:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion-item__text-details {
.accordion__details

2022-02-22 16:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    border: 1px solid #ACB5BD;
заберем из переменных?)

2022-02-22 16:00 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    color: #212429;
из переменных

2022-02-23 18:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-23 18:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-23 19:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-23 19:07 UTC, ShchetkinaAnna commented on 03-lection1/02-accordion/accordion.css
> +.accordion-item__summary {
Исправлено

2022-02-23 19:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-23 21:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-24 10:13 UTC, GSemikozov approved these changes

2022-02-24 10:13 UTC, merged